namespace UglyToad.PdfPig.Export.PAGE
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Xml.Serialization;

    /******************************************************************************
     * PAGE pagecontent version 2019-07-15 https://www.primaresearch.org/schema/PAGE/gts/pagecontent/2019-07-15/pagecontent.xsd
     * Auto-generated by xsd and improved by BobLD
     ******************************************************************************/

    /// <summary>
    /// PAGE (Page Analysis and Ground-Truth Elements) root
    /// <para>Version 2019-07-15</para>
    /// </summary>
    [EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15")]
    [XmlRootAttribute("PcGts", Namespace = "http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15", IsNullable = false)]
    public partial class PageXmlDocument
    {
        private PageXmlMetadata metadataField;

        private PageXmlPage pageField;

        private string pcGtsIdField;

        /// <remarks/>
        public PageXmlMetadata Metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        /// <remarks/>
        public PageXmlPage Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute("pcGtsId", DataType = "ID")]
        public string PcGtsId
        {
            get
            {
                return this.pcGtsIdField;
            }
            set
            {
                this.pcGtsIdField = value;
            }
        }
    }
}
