namespace UglyToad.PdfPig.Content
{
    using System;
    using System.Linq;
    using UglyToad.PdfPig.Core;
    using UglyToad.PdfPig.Tokens;

    /// <summary>
    /// Artifacts are graphics objects that are not part of the author’s original content but rather are 
    /// generated by the conforming writer in the course of pagination, layout, or other strictly mechanical 
    /// processes.
    /// <para>Artifacts may also be used to describe areas of the document where the author uses a graphical 
    /// background, with the goal of enhancing the visual experience. In such a case, the background is not 
    /// required for understanding the content. - PDF 32000-1:2008, Section 14.8.2.2</para>
    /// </summary>
    public class PdfArtifactMarkedContent : PdfMarkedContent
    {
        internal PdfArtifactMarkedContent(int id, DictionaryToken properties) : base(id, NameToken.Artifact, properties)
        {
            IsArtifact = true;
        }

        /// <summary>
        /// The artifact's type: Pagination, Layout, Page, or (PDF 1.7) Background.
        /// </summary>
        public ArtifactType Type
        {
            get
            {
                if (Properties == null) return ArtifactType.Unknown;
                if (Properties.TryGet(NameToken.Type, out IDataToken<string> typeToken))
                {
                    if (Enum.TryParse(typeToken.Data, true, out ArtifactType result))
                    {
                        return result;
                    }
                }
                return ArtifactType.Unknown;
            }
        }

        /// <summary>
        /// The artifact's attribute owners.
        /// </summary>
        public string AttributeOwners
        {
            get
            {
                if (Properties == null) return null;
                if (Properties.TryGet(NameToken.O, out IDataToken<string> typeToken))
                {
                    return typeToken.Data;
                }
                return null;
            }
        }

        /// <summary>
        /// The artifact's bounding box.
        /// </summary>
        public PdfRectangle? BoundingBox
        {
            get
            {
                if (Properties == null) return null;
                if (Properties.TryGet(NameToken.Bbox, out ArrayToken arrayToken))
                {
                    var left = arrayToken[2] as NumericToken;
                    var bottom = arrayToken[3] as NumericToken;
                    var right = arrayToken[4] as NumericToken;
                    var top = arrayToken[5] as NumericToken;
                    return new PdfRectangle((double)left.Data, (double)bottom.Data, (double)right.Data, (double)top.Data);
                }
                return null;
            }
        }

        /// <summary>
        /// Is the artifact attached to the top edge?
        /// </summary>
        public bool IsTopAttached => IsAttached("Top");

        /// <summary>
        /// Is the artifact attached to the bottom edge?
        /// </summary>
        public bool IsBottomAttached => IsAttached("Bottom");

        /// <summary>
        /// Is the artifact attached to the left edge?
        /// </summary>
        public bool IsLeftAttached => IsAttached("Left");

        /// <summary>
        /// Is the artifact attached to the right edge?
        /// </summary>
        public bool IsRightAttached => IsAttached("Right");

        /// <summary>
        /// The artifact's subtype. Standard values are Header, Footer, and Watermark. Additional values may be specified for this entry, provided they comply with the naming conventions.
        /// </summary>
        public string SubType
        {
            get
            {
                if (Properties == null) return null;
                if (Properties.TryGet(NameToken.Subtype, out IDataToken<string> subTypeToken))
                {
                    return subTypeToken.Data;
                }
                return null;
            }
        }

        private bool IsAttached(string edge)
        {
            if (Properties == null) return false;
            if (this.Properties.TryGet(NameToken.Attached, out ArrayToken arrayToken))
            {
                return arrayToken.Data.Contains(NameToken.Create(edge));
            }
            return false;
        }
    }

    /// <summary>
    /// If present, shall be one of the names Pagination, Layout, Page, or (PDF 1.7) Background.
    /// </summary>
    public enum ArtifactType
    {
        /// <summary>
        /// Unknown artifact type.
        /// </summary>
        Unknown,

        /// <summary>
        /// Ancillary page features such as running heads and folios (page numbers).
        /// </summary>
        Pagination,

        /// <summary>
        /// Purely cosmetic typographical or design elements such as footnote rules or background screens.
        /// </summary>
        Layout,

        /// <summary>
        /// Production aids extraneous to the document itself, such as cut marks and colour bars.
        /// </summary>
        Page,

        /// <summary>
        /// (PDF 1.7) Images, patterns or coloured blocks that either run the entire length and/or 
        /// width of the page or the entire dimensions of a structural element. Background artifacts 
        /// typically serve as a background for content shown either on top of or placed adjacent to 
        /// that background.
        /// <para>A background artifact can further be classified as visual content that serves to enhance the user experience, that lies under the actual content, and that is not required except to retain visual fidelity.</para>
        /// </summary>
        Background
    }
}
