name: Build and test [MacOS]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up dotnet core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            2.1.x
            6.0.x
            8.0.x
            
      # Build the release build
      - name: Build the solution
        run: dotnet build -c Release src/UglyToad.PdfPig.sln

      - name: Run the tests
        run: dotnet test -c Release src/UglyToad.PdfPig.sln
