name: Run Integration Tests

on:
  push:
    branches: [master]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore cached part 1
        id: restore-cache-p1
        uses: actions/cache@v4
        with:
          path: archive/part1-archive.7z
          key: ${{ runner.os }}-part-1

      - name: Restore cached part 2
        id: restore-cache-p2
        uses: actions/cache@v4
        with:
          path: archive/part2-archive.7z
          key: ${{ runner.os }}-part-2

      - name: Restore cached part 3
        id: restore-cache-p3
        uses: actions/cache@v4
        with:
          path: archive/part3-archive.7z
          key: ${{ runner.os }}-part-3

      - name: Download the archive part 1
        if: steps.restore-cache-p1.outputs.cache-hit != 'true'
        run: wget http://eliot-jones.com:8081/part1-archive.7z -nv -P archive/ && ls archive

      - name: Download the archive part 2
        if: steps.restore-cache-p2.outputs.cache-hit != 'true'
        run: wget http://eliot-jones.com:8081/part2-archive.7z -nv -P archive/ && ls archive

      - name: Download the archive part 3
        if: steps.restore-cache-p3.outputs.cache-hit != 'true'
        run: wget http://eliot-jones.com:8081/part3-archive.7z -nv -P archive/ && ls archive

      - name: Unzip archives
        run: sudo apt-get install p7zip-full && cd archive && 7z x part1-archive.7z && 7z x part2-archive.7z && 7z x part3-archive.7z

      - name: Run tests
        run: dotnet run --project tools/UglyToad.PdfPig.ConsoleRunner/UglyToad.PdfPig.ConsoleRunner.csproj "archive/"
